#!/bin/bash

# Make sure the agent is an executable
chmod +x ${OPENSHIFT_REPO_DIR}logentries/le

# If the pid file exists, the agent should be closed
if [ -f "${OPENSHIFT_DATA_DIR}logentries.pid" ];
then
    kill `cat ${OPENSHIFT_DATA_DIR}logentries.pid`
fi
